swagger: '2.0'
info:
  title: Azure DevOps MCP Connector
  description: Model Context Protocol connector for Azure DevOps work item management
  version: 1.0.0
host: copilotmcpdevfunc.azurewebsites.net
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /mcp:
    post:
      summary: Execute MCP Command
      description: Execute Model Context Protocol command for Azure DevOps operations
      operationId: ExecuteMCPCommand
      x-ms-visibility: important
      parameters:
        - name: x-functions-key
          in: header
          required: true
          type: string
          description: Azure Function authentication key
          x-ms-summary: Function Key
          x-ms-visibility: important
        - name: body
          in: body
          required: true
          description: MCP Request Body
          schema:
            type: object
            required:
              - method
            properties:
              method:
                type: string
                description: MCP method to execute
                x-ms-summary: Method
                enum:
                  - tools/list
                  - tools/call
                x-ms-visibility: important
              params:
                type: object
                description: Parameters for the method
                x-ms-summary: Parameters
                properties:
                  name:
                    type: string
                    description: Tool name (for tools/call)
                    x-ms-summary: Tool Name
                    enum:
                      - list_work_items
                      - get_work_item
                      - create_work_item
                      - update_work_item
                      - run_pipeline
                      - get_pipeline_status
                  arguments:
                    type: object
                    description: Arguments for the tool
                    x-ms-summary: Tool Arguments
                    properties:
                      project:
                        type: string
                        description: Azure DevOps project name
                        x-ms-summary: Project Name
                        default: "AI Space Team"
                      id:
                        type: integer
                        description: Work item ID
                        x-ms-summary: Work Item ID
                      title:
                        type: string
                        description: Work item title
                        x-ms-summary: Title
                      type:
                        type: string
                        description: Work item type
                        x-ms-summary: Type
                        enum:
                          - Task
                          - Bug
                          - User Story
                          - Feature
                          - Epic
                      description:
                        type: string
                        description: Work item description
                        x-ms-summary: Description
                      state:
                        type: string
                        description: Work item state
                        x-ms-summary: State
                        enum:
                          - New
                          - Active
                          - Resolved
                          - Closed
                      assigned_to:
                        type: string
                        description: Assigned to (email)
                        x-ms-summary: Assigned To
                      priority:
                        type: integer
                        description: Priority (1-4)
                        x-ms-summary: Priority
                        minimum: 1
                        maximum: 4
                      pipeline_id:
                        type: integer
                        description: Pipeline ID
                        x-ms-summary: Pipeline ID
                      branch:
                        type: string
                        description: Branch name
                        x-ms-summary: Branch
                        default: main
                      query:
                        type: string
                        description: WIQL query
                        x-ms-summary: Query
                      limit:
                        type: integer
                        description: Maximum items to return
                        x-ms-summary: Limit
                        default: 10
              id:
                type: integer
                description: Request ID
                default: 1
                x-ms-visibility: internal
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              result:
                type: object
                description: Result from MCP operation
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        text:
                          type: string
                  tools:
                    type: array
                    description: Available tools (for tools/list)
                    items:
                      type: object
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              error:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
definitions:
  MCPRequest:
    type: object
    properties:
      method:
        type: string
      params:
        type: object
      id:
        type: integer
  MCPResponse:
    type: object
    properties:
      result:
        type: object
      error:
        type: object
      id:
        type: integer
x-ms-connector-metadata:
  - propertyName: Website
    propertyValue: https://github.com/copilot365mcp
  - propertyName: Privacy policy
    propertyValue: https://github.com/copilot365mcp/privacy
  - propertyName: Categories
    propertyValue: AI;Productivity