swagger: '2.0'
info:
  title: Azure DevOps MCP Server
  description: MCP Server for Azure DevOps task management through Copilot Studio
  version: 1.0.0
host: copilotmcpdevfunc.azurewebsites.net
basePath: /api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /mcp:
    post:
      summary: Azure DevOps MCP API
      description: Handles MCP protocol requests for Azure DevOps operations
      operationId: InvokeMCP
      x-ms-visibility: important
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          default: application/json
          x-ms-visibility: internal
        - name: x-functions-key
          in: header
          required: true
          type: string
          description: Azure Function Key for authentication
          x-ms-summary: Function Key
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - method
            properties:
              method:
                type: string
                description: MCP method to invoke
                x-ms-summary: Method
                enum:
                  - tools/list
                  - tools/call
                default: tools/list
              params:
                type: object
                description: Parameters for the method
                x-ms-summary: Parameters
              id:
                type: integer
                description: Request ID
                default: 1
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                description: JSON-RPC version
              id:
                type: integer
                description: Request ID
              result:
                type: object
                description: Result data
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  API Key:
    type: apiKey
    in: header
    name: x-functions-key
security:
  - API Key: []
tags: []