swagger: '2.0'
info:
  title: Azure DevOps List Work Items
  description: Simple connector to list work items from Azure DevOps via MCP
  version: 1.0.0
host: copilotmcpdevfunc.azurewebsites.net
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: x-functions-key
security:
  - apiKey: []
paths:
  /mcp:
    post:
      summary: List Work Items
      description: Get list of work items from Azure DevOps project
      operationId: ListWorkItems
      parameters:
        - name: projectName
          in: query
          type: string
          required: false
          description: Project name (defaults to AI Space Team)
          x-ms-summary: Project Name
          x-ms-visibility: advanced
        - name: body
          in: body
          required: true
          schema:
            type: object
            default:
              method: "tools/call"
              params:
                name: "list_work_items"
                arguments:
                  project: "AI Space Team"
              id: 1
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              result:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        text:
                          type: string